version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=example
      - DB_HOST=psql
      - DB_DATABASE=postgres
      - DB_USER=postgres
    depends_on:
      - psql
    links:
      - psql
  psql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example